Repository ant-design-blazor/blazor-pro-components, pull requests merged in 2020-11, with the labels that each got.

#10 fix: remove Message container from SettingDrawer
  example/AntDesign.Pro.Layout.Wasm/App.razor
  src/SettingDrawer/SettingDrawer.razor
Labels: PR: merged

#11 upgrade: upgrade to .net5.0
  .github/workflows/package.yml
  .github/workflows/pr-checks.yml
  example/AntDesign.Pro.Layout.Wasm/AntDesign.Pro.Layout.Wasm.csproj
  example/AntDesign.Pro.Layout.Wasm/Program.cs
  example/AntDesign.Pro.Layout.Wasm/Properties/launchSettings.json
  example/AntDesign.Pro.Layout.Wasm/_Imports.razor
  example/AntDesign.Pro.Layout.Wasm/wwwroot/index.html
  example/AntDesign.Pro.Layout.Wasm/wwwroot/service-worker.js
  example/AntDesign.Pro.Layout.Wasm/wwwroot/service-worker.published.js
  src/AntDesign.Pro.Layout.csproj
Labels: PR: reviewed-approved

#12 [fix](module: noticelist) dropdown can not be closed
  src/NoticeIcon/NoticeIcon.razor
  src/NoticeIcon/NoticeIcon.razor.cs
Labels: PR: reviewed-approved

#13 [fix](module: sidermenu) collapse button always highlight
  src/BasicLayout.razor.cs
  src/SiderMenu/SiderMenu.razor
  src/SiderMenu/SiderMenu.razor.cs
  src/TopNavHeader/TopNavHeader.razor.cs
Labels: PR: unreviewed

#14 [fix](module: layout) incorrect usage of select
  example/AntDesign.Pro.Layout.Wasm/Shared/ProLayout.razor
  src/SettingDrawer/LayoutSetting.razor
Labels: PR: reviewed-approved
